import os
import json
import glob

def generate_card_html(key, item):
    """
    为每个经济指标生成一对卡片：数据卡 (左) + 分析卡 (右)
    """
    name = item.get("name", "未知指标")
    month = item.get("month", "N/A")
    
    # 针对不同指标提取主数值
    value = item.get("mfg") if key == "pmi" else item.get("value", 0.0)
    # 重点：再次强制确保 yoy 不是 None
    yoy_raw = item.get("mfg_yoy") if key == "pmi" else item.get("yoy", 0.0)
    yoy = float(yoy_raw) if yoy_raw is not None else 0.0
    
    # 动态判断颜色和图标
    color_class = "text-emerald-500" if yoy >= 0 else "text-rose-500"
    icon_name = "trending-up" if yoy >= 0 else "trending-down"
    
    # yoy 展示逻辑
    yoy_display = f"{yoy:+.1f}%" if yoy != 0 else "--"

    # AI 分析内容
    ai_insight = item.get("ai_insight", "AI 正在深度解析该项指标的结构性变化...")

    return f"""
    <section class="space-y-6 animate-card">
        <div class="flex items-center gap-2 text-xl font-bold text-slate-700">
            <i data-lucide="layers" class="w-6 h-6"></i>
            <h2>{name} <span class="text-sm font-normal text-slate-400 ml-2">{month}</span></h2>
        </div>
        <div class="grid grid-cols-1 lg:grid-cols-3 gap-6">
            <div class="lg:col-span-1 glass-card p-8 rounded-3xl shadow-sm border border-white/40">
                <div class="flex justify-between items-start mb-6">
                    <span class="px-3 py-1 bg-slate-100 text-slate-500 text-xs font-bold rounded-full uppercase tracking-tighter">Live</span>
                    <i data-lucide="database" class="text-blue-500 w-5 h-5"></i>
                </div>
                <div class="space-y-1">
                    <p class="text-sm font-medium text-slate-400 uppercase tracking-widest">指标数值</p>
                    <div class="flex items-baseline gap-2">
                        <h3 class="text-6xl font-black text-slate-800 tracking-tighter">{float(value):.1f}</h3>
                        <span class="{color_class} font-bold flex items-center text-sm">
                            <i data-lucide="{icon_name}" class="w-4 h-4 mr-1"></i> {yoy_display}
                        </span>
                    </div>
                </div>
            </div>
            <div class="lg:col-span-2 glass-card p-8 rounded-3xl shadow-sm border border-white/40">
                <div class="flex items-center gap-2 mb-4 text-blue-600">
                    <i data-lucide="sparkles" class="w-5 h-5"></i>
                    <span class="text-sm font-bold uppercase tracking-widest">AI Analyst Perspective</span>
                </div>
                <article class="prose prose-slate max-w-none text-slate-600 leading-relaxed">
                    {ai_insight}
                </article>
            </div>
        </div>
    </section>
    """

def build_page(json_data):
    update_time = json_data.get("update_time", "Unknown")
    metrics = json_data.get("metrics", {})
    all_cards_html = "".join([generate_card_html(k, v) for k, v in metrics.items() if v.get("status") == "success"])

    template = f"""
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Economy Insider</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://unpkg.com/lucide@latest"></script>
    <style>
        @keyframes slideUp {{ from {{ opacity: 0; transform: translateY(20px); }} to {{ opacity: 1; transform: translateY(0); }} }}
        .animate-card {{ animation: slideUp 0.6s ease-out forwards; }}
        .glass-card {{ background: rgba(255, 255, 255, 0.75); backdrop-filter: blur(16px); }}
    </style>
</head>
<body class="bg-slate-50 text-slate-900 font-sans tracking-tight">
    <header class="py-16 px-6 max-w-7xl mx-auto flex justify-between items-end">
        <div>
            <h1 class="text-5xl font-black tracking-tighter text-slate-900">ECONOMY <span class="text-blue-600 italic">INSIDER</span></h1>
            <p class="mt-2 text-slate-400 font-medium tracking-wide">数据驱动的宏观内参系统</p>
        </div>
        <div class="text-right">
            <p class="text-xs font-bold text-slate-300 uppercase tracking-widest">Updated At</p>
            <p class="text-sm font-mono text-slate-500">{update_time}</p>
        </div>
    </header>
    <main class="max-w-7xl mx-auto px-6 pb-24 space-y-16">
        {all_cards_html}
    </main>
    <footer class="text-center py-20 border-t border-slate-200 text-slate-300 text-[10px] uppercase tracking-[0.2em]">
        &copy; 2026 Bjarne Yang | Generated by Gemini 2.0
    </footer>
    <script>lucide.createIcons();</script>
</body>
</html>
    """
    
    # 网页生成在根目录 (src 的上一级)
    output_path = os.path.join("..", "index.html")
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(template)
    print(f"✨ [成功] index.html 已生成至根目录: {os.path.abspath(output_path)}")

if __name__ == "__main__":
    # 路径处理：去上一级目录找 data
    data_pattern = os.path.join("..", "data", "*.json")
    list_of_files = glob.glob(data_pattern)
    
    if list_of_files:
        latest_file = max(list_of_files, key=os.path.getctime)
        print(f"📖 [读取] 正在处理最新数据文件: {latest_file}")
        with open(latest_file, 'r', encoding='utf-8') as f:
            data = json.load(f)
            build_page(data)
    else:
        print("❌ [错误] 未在 ../data 目录下找到任何 JSON 文件，请先运行 data_fetcher.py")